project-name: Elizabeth Bugbey
project-tagline: Career Product Manager turned Data Scientist. Expert at bridging the gap between technology/data and business impact.
show_downloads: TRUE
theme: jekyll-theme-cayman
